name: Validation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn install

      - name: Run TSLint
        run: yarn run lint
